model:
  class: "contact_graspnet.models.ContactGraspnet"
  config_path: "~/Documents/ContactGraspnetBenchmark/contact_graspnet/checkpoints/scene_test_2048_bs3_hor_sigma_001/config.yaml"
  checkpoint_dir: "~/Documents/ContactGraspnetBenchmark/contact_graspnet/checkpoints/scene_test_2048_bs3_hor_sigma_001"

dataset:
  class: "contact_graspnet.dataloading.YCBSimulationData"
  root_dir: "~/Documents/ycb_sim_data_1"
  invalid_objs: [018_pitcher_base", "019_bleach_cleanser", "021_bowl", "025_plate", "026_fork", "039_hammer", "042_large_clamp", "056_b_cups", "058_d_cups", "059_e_cups", "084_j_lego_duplo"]
  transform:
    class: "contact_graspnet.preprocessing.UniversalPreprocessor"
    depth2points_converter:
      class: "contact_graspnet.preprocessing.Depth2ImgPoints"
    img2cam_converter:
      class: "contact_graspnet.preprocessing.Img2CamCoords"
    z_clipper:
      class: "contact_graspnet.preprocessing.ZClipper"
      z_range: [0.2, 1.8]
    segmentation_binarizer: null
      # class: "contact_graspnet.preprocessing.SegmentationBinarizer"
      # segmentation_id: 1.0
    resizer: null
      # class: "contact_graspnet.preprocessing.Resizer"
      # target_size: [720, 1280]

postprocessor:
  class: "contact_graspnet.postprocessing.Postprocessor"
  top_score_filter: null 
    # class: "contact_graspnet.postprocessing.TopSoreFilter"
    # top_k: 3 

result_path: "~/Documents/ContactGraspnetBenchmark/contact_graspnet/data/results/ycb1_no_resize"
  